apiVersion: v1
kind: Service
metadata:
  name: ai-travel-agent-service
spec:
  selector:
    app: ai-travel-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
